
identity:
  # This will be the default JSON Schema. If `schema_id` is empty when creating an identity using the
  # Admin API, or a user signs up using a selfservice flow, this schema will be used.
  #
  # This is a required configuration field!
  default_schema_url: file:///etc/config/kratos/identity.schema.json

selfservice:
  methods:
    password:
      enabled: true

  default_browser_return_url: http://127.0.0.1:3000/dashboard
  # whitelisted_return_urls:
  #   - http://127.0.0.1:3000/dashboard

  flows:
    logout:
      after:
        default_browser_return_url: http://localhost:3000/login
    settings:
      ui_url: http://localhost:3000/settings
    login:
      ui_url: http://localhost:3000/login
      lifespan: 10m
    registration:
      ui_url: http://localhost:3000/register

serve:
  admin:
    base_url:  http://127.0.0.1:4445
  public:
    base_url: http://127.0.0.1:4445/.ory/kratos/public

dsn: postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

log:
  level: debug

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16